import { Geist, Geist_Mono , Inter } from "next/font/google";
import "./globals.css";

// shadcn ui 
import { cn } from "@/lib/utils"
// global toast 
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learning Management System",
  description: "Generated by create next app",
};

const poppins = Inter({
  variable: "--font-poppins",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased , poppins.className`)}
      >
        {children}
        <Toaster richColors position='top-center'/>
      </body>
    </html>
  );
}
